#!/bin/bash

server_name="automautic.mktg.dev-$(printf "%04d" $RANDOM)"

server_ip=""

while [ -z "$server_ip" ]; do
  echo "Waiting for server to become ready..."
  sleep 2

  response=$(curl -s \
    -X POST \
    -H "Authorization: Bearer $HETZNER_API_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{
      "name": "'"$server_name"'",
      "server_type": "cpx21",
      "image": "ubuntu-24.04",
      "location": "nbg1",
      "ssh_keys": ["yosu@Debian-12"]
    }' \
    https://api.hetzner.cloud/v1/servers)

  # Check for curl errors
  if [[ $? -ne 0 ]]; then
      echo "Error: curl command failed."
      exit 1
  fi

  # Save the response to a file (optional, for debugging)
  echo "$response" > response.json

  server_ip=$(echo "$response" | jq -r '.server.public_net.ipv4.ip')
  server_status=$(echo "$response" | jq -r '.server.status')

  if [ "$server_status" = "running" ]; then
    break
  fi

  if [ "$server_status" = "error" ]; then
    error_message=$(echo "$response" | jq -r '.error.message')
    error_code=$(echo "$response" | jq -r '.error.code')

    echo "Error creating server:"
    echo "  Message: $error_message"
    echo "  Code: $error_code"
    echo "  Details: $(echo "$response" | jq -r '.error.details')"

    exit 1
  fi
done

echo "Server IP: $server_ip"
echo "Server Name: $server_name"
